#!/usr/bin/env python3
"""Compare build-artifact mtimes against source mtimes (hard-contract freshness).

Default mode is **per-unit**: each artifact is judged only against sources under
the same package unit (directory walk-up to Makefile/CMake/zproject or scope
root). This avoids monorepo false STALE when an unrelated tree is newer.

Use --global for the old behaviour (any source newer → all artifacts STALE).

Exit codes:
  0 = all considered artifacts are fresh
  1 = stale or insufficient evidence (not proof for EXACTO)
  2 = usage / path error
"""
from __future__ import annotations

import argparse
import time
from pathlib import Path

from scan_common import (
    ASM_EXTS,
    BINARY_ARTIFACT_EXTS,
    C_EXTS,
    LISTING_EXTS,
    SOURCE_EXTS,
    TEXT_BUILD_EXTS,
    is_host_only_path,
    rel_path,
    resolve_scope,
)

ARTIFACT_EXTS = TEXT_BUILD_EXTS | LISTING_EXTS | BINARY_ARTIFACT_EXTS | {".asm"}
SOURCE_ONLY = SOURCE_EXTS | C_EXTS | ASM_EXTS | {".opt", ".rul", ".mk"}

UNIT_MARKERS = {
    "Makefile",
    "makefile",
    "GNUmakefile",
    "CMakeLists.txt",
    "zproject.lst",
    "project.lk",
    "build.mk",
    "package.json",  # rare on Z80; harmless
}
GENERATED_SOURCE_MARKERS = ("auto-generated", "autogenerated", "generated by", "do not edit")
AMBIGUOUS_ASSET_EXTS = {".bin", ".scr"}
OUTPUT_DIRS = {"build", "obj", "out", "dist", "tmp", "gen", "generated"}


def mtime(path: Path) -> float:
    try:
        return path.stat().st_mtime
    except OSError:
        return 0.0


def is_generated_asm(path: Path) -> bool:
    parts = {p.lower() for p in path.parts}
    return path.suffix.lower() in ASM_EXTS and bool(
        parts & {"build", "obj", "out", "gen", "generated", "tmp", "dist"}
    )


def is_declared_generated_source(path: Path) -> bool:
    try:
        head = path.read_text(encoding="utf-8", errors="ignore")[:4096].lower()
    except OSError:
        return False
    return any(marker in head for marker in GENERATED_SOURCE_MARKERS)


def classify(path: Path) -> str:
    suf = path.suffix.lower()
    if suf in {".map", ".sym", ".lst", ".lis", ".rel", ".ihx", ".lk", ".noi", ".mem"}:
        return "artifact"
    if suf in BINARY_ARTIFACT_EXTS:
        parts = {part.lower() for part in path.parts}
        if suf in AMBIGUOUS_ASSET_EXTS and not (parts & OUTPUT_DIRS):
            return "source"
        return "artifact"
    if is_generated_asm(path):
        return "artifact"
    if suf in SOURCE_ONLY or path.name in {
        "Makefile",
        "makefile",
        "GNUmakefile",
        "CMakeLists.txt",
    }:
        return "source"
    return "other"


def unit_root(path: Path, scope_base: Path) -> Path:
    """Package unit: walk up from path to a build marker or scope base."""
    cur = path if path.is_dir() else path.parent
    scope_base = scope_base.resolve()
    try:
        cur.relative_to(scope_base)
    except ValueError:
        return scope_base
    while True:
        if cur == scope_base:
            return scope_base
        for name in UNIT_MARKERS:
            if (cur / name).exists():
                return cur
        # treat src/ parent as unit when artifact lives in sibling build/
        if cur.name.lower() in {"build", "obj", "out", "gen", "generated", "dist", "tmp"}:
            parent = cur.parent
            if parent == scope_base or any((parent / m).exists() for m in UNIT_MARKERS):
                return parent
        if cur.parent == cur:
            return scope_base
        cur = cur.parent


def under(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
        return True
    except ValueError:
        return False


def relevant_sources(
    art: Path,
    sources: list[Path],
    scope_base: Path,
    mode: str,
    touched: set[Path] | None,
) -> list[Path]:
    if mode == "global":
        pool = list(sources)
    else:
        unit = unit_root(art, scope_base)
        pool = [s for s in sources if under(s, unit)]
        # Monorepo guard: if unit is the scope root, ignore sources that live in a
        # *nested* package unit that does not contain this artifact (e.g. pkg_b/
        # must not stale build/ maps that belong to no nested unit / another unit).
        if unit.resolve() == scope_base.resolve():
            filtered: list[Path] = []
            for s in pool:
                s_unit = unit_root(s, scope_base)
                if s_unit.resolve() != scope_base.resolve() and not under(art, s_unit):
                    continue
                filtered.append(s)
            if filtered:
                pool = filtered
        if not pool:
            pool = list(sources)
    if touched:
        touched_res = {p.resolve() for p in touched}
        pool = [s for s in pool if s.resolve() in touched_res]
    return pool


def staged_generated_for(
    artifact: Path, sources: list[Path], scope_base: Path, mode: str
) -> set[Path]:
    if mode != "per-unit":
        return set()
    artifact_unit = unit_root(artifact, scope_base).resolve()
    return {
        source.resolve()
        for source in sources
        if is_declared_generated_source(source)
        and unit_root(source, scope_base).resolve() == artifact_unit
        and mtime(artifact) >= mtime(source)
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Hard-contract freshness: map/listing/bin vs current sources"
    )
    parser.add_argument("target", nargs="?", default=".")
    parser.add_argument(
        "--skew-seconds",
        type=int,
        default=2,
        help="allow artifact to be this many seconds older than newest relevant source (default 2)",
    )
    parser.add_argument(
        "--mode",
        choices=("per-unit", "global"),
        default="per-unit",
        help="per-unit (default): only sources in same package unit; global: any source",
    )
    parser.add_argument(
        "--touched",
        nargs="*",
        default=None,
        help="optional list of source paths; only these count as changers (CI-style)",
    )
    args = parser.parse_args()
    target = Path(args.target).resolve()
    if not target.exists():
        print(f"error: missing target {target}")
        return 2

    scope = resolve_scope(target, SOURCE_ONLY | ARTIFACT_EXTS | {".opt", ".rul"})
    sources: list[Path] = []
    artifacts: list[Path] = []
    for path in scope.files:
        kind = classify(path)
        if kind == "source" and not is_host_only_path(path, scope.base):
            sources.append(path)
        elif kind == "artifact":
            artifacts.append(path)

    touched: set[Path] | None = None
    if args.touched:
        touched = set()
        for raw in args.touched:
            tp = Path(raw).resolve()
            if tp.exists():
                touched.add(tp)
            else:
                print(f"warning: --touched missing {raw}")

    if not artifacts:
        print("status: NO_ARTIFACTS")
        print("note: no map/listing/bin under scope; cannot prove sizes from build")
        print("verdict: REQUIERE_BUILD")
        return 1

    if not sources:
        print("status: NO_SOURCES")
        print("note: artifacts present but no sources in scope; treat sizes as triage only")
        print("verdict: SUSPICIOUS")
        return 1

    staged_generated = set().union(
        *(staged_generated_for(art, sources, scope.base, args.mode) for art in artifacts)
    )

    newest_src = max(sources, key=mtime)
    newest_src_mt = mtime(newest_src)
    oldest_art = min(artifacts, key=mtime)
    newest_art = max(artifacts, key=mtime)

    print(f"root: {scope.target}")
    print(f"mode: {args.mode}")
    print(f"sources: {len(sources)}")
    print(f"artifacts: {len(artifacts)}")
    if touched is not None:
        print(f"touched_filter: {len(touched)} paths")
    print(
        f"newest_source_global: {rel_path(newest_src, scope.base)} mtime={int(newest_src_mt)} "
        f"({time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(newest_src_mt))})"
    )
    print(
        f"newest_artifact: {rel_path(newest_art, scope.base)} mtime={int(mtime(newest_art))}"
    )
    print(
        f"oldest_artifact: {rel_path(oldest_art, scope.base)} mtime={int(mtime(oldest_art))}"
    )
    print(
        "note: default per-unit ignores unrelated monorepo sources; "
        "use --mode global for strict whole-tree freshness"
    )
    print("\n[staged_generated_sources]")
    if not staged_generated:
        print("none")
    else:
        for source in sorted(staged_generated, key=str):
            print(f"  STAGED {rel_path(source, scope.base)} mtime={int(mtime(source))}")
        print(
            "  note: declared generated sources followed by a same-unit artifact "
            "do not stale earlier build stages; --mode global remains strict"
        )

    stale: list[tuple[Path, float, float, Path | None, Path]] = []
    fresh: list[tuple[Path, Path]] = []
    for art in sorted(artifacts, key=lambda p: str(p)):
        amt = mtime(art)
        unit = unit_root(art, scope.base)
        rel_srcs = relevant_sources(art, sources, scope.base, args.mode, touched)
        staged_for_artifact = staged_generated_for(
            art, rel_srcs, scope.base, args.mode
        )
        rel_srcs = [
            source for source in rel_srcs if source.resolve() not in staged_for_artifact
        ]
        if not rel_srcs:
            # no relevant sources → cannot prove; treat as SUSPICIOUS/stale-ish
            stale.append((art, amt, 0.0, None, unit))
            continue
        newest_rel = max(rel_srcs, key=mtime)
        nmt = mtime(newest_rel)
        if nmt > amt + args.skew_seconds:
            stale.append((art, amt, nmt - amt, newest_rel, unit))
        else:
            fresh.append((art, unit))

    print("\n[fresh_artifacts]")
    if not fresh:
        print("none")
    else:
        for path, unit in fresh[:40]:
            print(
                f"  FRESH {rel_path(path, scope.base)} mtime={int(mtime(path))} "
                f"unit={rel_path(unit, scope.base)}"
            )
        if len(fresh) > 40:
            print(f"  ... {len(fresh) - 40} more")

    print("\n[stale_artifacts]")
    if not stale:
        print("none")
    else:
        for path, amt, lag, cause, unit in stale[:40]:
            cause_s = rel_path(cause, scope.base) if cause else "n/a"
            print(
                f"  STALE {rel_path(path, scope.base)} mtime={int(amt)} "
                f"lag_vs_relevant_source={int(lag)}s "
                f"caused_by={cause_s} unit={rel_path(unit, scope.base)}"
            )
        if len(stale) > 40:
            print(f"  ... {len(stale) - 40} more")

    maps = [p for p in artifacts if p.suffix.lower() == ".map"]
    print("\n[map_freshness]")
    if not maps:
        print("none")
    else:
        for path in maps:
            unit = unit_root(path, scope.base)
            rel_srcs = relevant_sources(path, sources, scope.base, args.mode, touched)
            staged_for_artifact = staged_generated_for(
                path, rel_srcs, scope.base, args.mode
            )
            rel_srcs = [
                source
                for source in rel_srcs
                if source.resolve() not in staged_for_artifact
            ]
            amt = mtime(path)
            if not rel_srcs:
                tag = "STALE"
            else:
                nmt = mtime(max(rel_srcs, key=mtime))
                tag = "STALE" if nmt > amt + args.skew_seconds else "FRESH"
            print(
                f"  {tag} {rel_path(path, scope.base)} mtime={int(amt)} "
                f"unit={rel_path(unit, scope.base)}"
            )

    # Info-only: would global mode have differed?
    global_stale = 0
    for art in artifacts:
        if newest_src_mt > mtime(art) + args.skew_seconds:
            global_stale += 1
    print("\n[global_mode_info]")
    print(f"  artifacts_stale_if_global: {global_stale}/{len(artifacts)}")
    print(
        "  note: if per-unit is FRESH but global would STALE, an unrelated tree is newer — OK for local claims"
    )

    if stale:
        print("\nverdict: STALE")
        print(
            "policy: do not promote EXACTO/CONFIRMED from stale maps/listings; "
            "label REQUIERE_BUILD or rebuild in disposable worktree first"
        )
        return 1

    print("\nverdict: FRESH")
    print("policy: artifacts may support EXACTO only after local symbol/byte re-check")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
